### ISSUE TITLE
change label of button to add supervisor of dissertation

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backend#407]
**Describe the improvement**
Currently, the button is named "publication.contributor.role.supervisor".  Change this to "Add supervisor".

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/172865372-f7c424c8-f8a1-42bd-9f7f-0c7ba583289b.png)

**Comment by sdebodt** [comment]
also remarked by a researcher.

**Comment by nicolasfranck** [comment]
Fixed since https://github.com/ugent-library/biblio-backend/commit/99b584e603f8f8f0453b4604d638494af4db4a23

(see [internal/translations/translations.go](https://github.com/ugent-library/biblio-backend/commit/99b584e603f8f8f0453b4604d638494af4db4a23#diff-d577a014d579ae7a37f60f0dbdf2caaf7a5076e5182c9ff1894989324f6c9f8c))

But not yet on backend.bibliotest.ugent.be?

**Comment by sdebodt** [comment]
indeed fixed on eliot1 .
no update of backend.bibliotest has been done for quite some time, so is not fixed there yet.
